Feature/column block
sewebb/iis-blocks pull request #3
Opened 2020-05-25 08:43 UTC by emelie

Column block with option to choose column width.

2020-05-25 11:50 UTC, tbleckert approved these changes

2020-05-25 12:21 UTC, tbleckert requested changes

2020-05-25 12:21 UTC, tbleckert commented on src/js/blocks/Column.jsx
> +            <InnerBlocks allowedBlocks={['iis/puff']} />
@emelie Är det dumt att tillåta alla block här? Tänker om man kanske vill göra en grid med bilder

2020-05-25 12:21 UTC, tbleckert commented on src/js/blocks/Column.jsx
> +    big: {
Den här kan försvinna, jag som råkade lämna kvar den när jag duplicerade info blocket :P

2020-05-26 07:18 UTC, emelie commented on src/js/blocks/Column.jsx
> +            <InnerBlocks allowedBlocks={['iis/puff']} />
Det borde ju inte vara ett problem, nej! Tar bort allowedBlocks.

2020-05-26 07:19 UTC, emelie commented on src/js/blocks/Column.jsx
> +    big: {
Tar bort det! :)

2020-05-26 07:20 UTC, tbleckert approved these changes

2020-05-26 07:21 UTC, merged